name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Enable Flutter iOS
        run: flutter config --enable-ios

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Upgrade Dependencies
        run: flutter pub upgrade

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install && cd ..

      - name: Set Up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -version

      - name: Clean and Build Flutter iOS
        run: |
          flutter clean
          flutter build ios --no-codesign --release

      - name: Compile Unsigned IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            build CODE_SIGNING_ALLOWED=NO

      - name: Package IPA
        run: |
          mkdir -p output
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath ../output \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v3
        with:
          name: unsigned-ipa
          path: output
